"""phase1 answer rate tables

Revision ID: 64de86ec20a4
Revises: 9e4d1003e934
Create Date: 2026-06-05 21:16:19.526971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64de86ec20a4'
down_revision: Union[str, None] = '9e4d1003e934'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('abandon_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('skill_group', sa.String(length=255), nullable=True),
    sa.Column('threshold_seconds', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('call_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('stat_date', sa.Date(), nullable=False),
    sa.Column('time_slot', sa.Integer(), nullable=False),
    sa.Column('skill_group', sa.String(length=255), nullable=False),
    sa.Column('completed_count', sa.Integer(), nullable=False),
    sa.Column('valid_abandon_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stat_date', 'time_slot', 'skill_group', name='uq_call_stats_date_slot_group')
    )
    op.create_table('exclude_numbers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('caller_number', sa.String(length=50), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('import_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('encoding', sa.String(length=50), nullable=True),
    sa.Column('row_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('imported_at', sa.DateTime(), nullable=False),
    sa.Column('engine_version', sa.String(length=50), nullable=True),
    sa.Column('threshold_rule_snapshot_json', sa.JSON(), nullable=True),
    sa.Column('exclude_numbers_snapshot_hash', sa.String(length=64), nullable=True),
    sa.Column('definition_note', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('op_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('skill_group', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('shift_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('op_code')
    )
    op.create_table('skill_group_merge',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('merge_label', sa.String(length=255), nullable=False),
    sa.Column('child_skill_group', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # 注意: autogenerate は既存テーブル(projects/tasks/teams/users)への
    # NOT NULL / FK / unique 変更も検出するが、これは ensure_*_columns の手書きALTERで
    # 作られた現行スキーマと entities.py の宣言差分にすぎない。
    # 本リビジョンは「新規テーブルの追加のみ」を範囲とするため、既存テーブルへの変更は
    # 意図的に除外している（会社方針: 既存テーブル変更は最小限／Phase1は新規追加のみ）。
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('skill_group_merge')
    op.drop_table('operators')
    op.drop_table('import_log')
    op.drop_table('exclude_numbers')
    op.drop_table('call_stats')
    op.drop_table('abandon_rules')
    # ### end Alembic commands ###
